import argparse
from PBOption import PBOption, addToParser, KNOWN_SITES_HELP
from PBOption import \
        ARG_GROUP_IO_OPTIONS, IO_OPTIONS, \
        ARG_GROUP_TOOL_OPTIONS, TOOL_OPTIONS,\
        ARG_GROUP_PERF_OPTIONS, PERF_OPTIONS, \
        ARG_GROUP_RUN_OPTIONS, RUN_OPTIONS
from pbutils import IsFileReadable, IsFileStreamWritable, IsBamValid
from minimap2OptionGenerator import minimap2OptionGenerator
from deepvariantOptionGenerator import deepvariantOptionGenerator
from sysOptionGenerator import sysOptionGenerator
import PbHelpFormatter

def ont_germline(argList):
    ont_germline_parser = argparse.ArgumentParser(
        description="Run the germline pipeline from FASTQ/BAM to VCF by aligning long read ONT sequences with minimap2 and using a deep neural network analysis.",
        formatter_class=PbHelpFormatter.PbHelpFormatter, #argparse.ArgumentDefaultsHelpFormatter,
        usage='''pbrun ont_germline <options>\nHelp: pbrun ont_germline -h''')
    IOOptions = [PBOption(category="IOOption", name="--ref", helpStr="Path to the reference file.", required=True, typeName=IsFileReadable),
                 PBOption(category="IOOption", name="--index", helpStr="Path to a minimizer index file generated by vanilla minimap2 to reduce indexing time.", required=False, typeName=IsFileReadable),
                 PBOption(category="IOOption", name="--in-fq", helpStr="Path to a query sequence file in fastq or fastq.gz format. This option can be used multiple times.", required=False, nargs='*', action='append', typeName=IsFileReadable),
                 PBOption(category="IOOption", name="--in-bam", helpStr="Path to the input BAM/CRAM file.", required=False, typeName=IsBamValid),
                 PBOption(category="IOOption", name="--jump-bed", short_name="-j", required=False, typeName=IsFileReadable, helpStr="Path to a BED file (.bed) used in the splice:sr preset for jumping junctions in the annotation."),
                 PBOption(category="IOOption", name="--junc-bed", required=False, typeName=IsFileReadable, helpStr="Path to a BED file (.bed) used in adding bonus scores if an aligned junction matches a junction in the annotation."),
                 PBOption(category="IOOption", name="--knownSites", action='append', typeName=IsFileReadable, helpStr=KNOWN_SITES_HELP),
                 PBOption(category="IOOption", name="--interval-file", action='append', typeName=IsFileReadable,
                          helpStr="Path to an interval file in one of these formats: Picard-style (.interval_list or .picard), GATK-style (.list or .intervals), or BED file (.bed). This option can be used multiple times."),
                 PBOption(category="IOOption", name="--pb-model-file", typeName=IsFileReadable,
                          helpStr="Path to a non-default parabricks model file for deepvariant."),
                 PBOption(category="IOOption", name="--pb-small-model-file", typeName=IsFileReadable,
                          helpStr="Path to a non-default parabricks model file for the small model."),
                 PBOption(category="IOOption", name="--out-recal-file", typeName=IsFileStreamWritable,
                          helpStr="Path of the report file after Base Quality Score Recalibration."),
                 PBOption(category="IOOption", name="--out-bam", typeName=IsFileStreamWritable,
                          helpStr="Path of BAM file after marking duplicates.", required=True),
                 PBOption(category="IOOption", name="--out-variants", typeName=IsFileStreamWritable,
                          helpStr="Path of the vcf/vcf.gz/gvcf/gvcf.gz file after variant calling.", required=True),
                 PBOption(category="IOOption", name="--out-duplicate-metrics", typeName=IsFileStreamWritable,
                          helpStr="Path of a duplicate metrics file after marking duplicates."),
                 PBOption(category="IOOption", name="--proposed-variants", typeName=IsFileReadable,
                          helpStr="Path of the VCF file, which has proposed variants for the make examples stage.")]
    ont_germline_parser_iogroup = ont_germline_parser.add_argument_group(ARG_GROUP_IO_OPTIONS, IO_OPTIONS)
    addToParser(ont_germline_parser_iogroup, IOOptions)

    minimapOpts = minimap2OptionGenerator(is_ont_germline=True)
    dvOpts = deepvariantOptionGenerator(is_pipeline=True, is_ont_germline=True)
    ont_germline_parser_toolgroup = ont_germline_parser.add_argument_group(ARG_GROUP_TOOL_OPTIONS, TOOL_OPTIONS)
    addToParser(ont_germline_parser_toolgroup, minimapOpts.allOptions)
    addToParser(ont_germline_parser_toolgroup, dvOpts.allOptions)

    ont_germline_parser_perfgroup = ont_germline_parser.add_argument_group(ARG_GROUP_PERF_OPTIONS, PERF_OPTIONS)
    addToParser(ont_germline_parser_perfgroup, minimapOpts.perfOptions)
    addToParser(ont_germline_parser_perfgroup, dvOpts.perfOptions)

    ont_germline_parser_sysgroup = ont_germline_parser.add_argument_group(ARG_GROUP_RUN_OPTIONS, RUN_OPTIONS)
    addToParser(ont_germline_parser_sysgroup, sysOptionGenerator().allOptions)

    args = ont_germline_parser.parse_args(argList[2:])
    return args
