import argparse
from PBOption import PBOption, addToParser, KNOWN_SITES_HELP
from PBOption import \
        ARG_GROUP_IO_OPTIONS, IO_OPTIONS, \
        ARG_GROUP_TOOL_OPTIONS, TOOL_OPTIONS,\
        ARG_GROUP_PERF_OPTIONS, PERF_OPTIONS, \
        ARG_GROUP_RUN_OPTIONS, RUN_OPTIONS
from pbutils import IsFileReadable, IsFileStreamWritable, IsDirWriteable, IsBamValid
from sysOptionGenerator import sysOptionGenerator
from minimap2OptionGenerator import minimap2OptionGenerator
import PbHelpFormatter

def minimap2(argList):
    minimap2_parser = argparse.ArgumentParser(
        description="Align long read sequences against a large reference database to convert FASTQ to BAM/CRAM.",
        formatter_class=PbHelpFormatter.PbHelpFormatter, #argparse.ArgumentDefaultsHelpFormatter,
        usage='''pbrun minimap2 [<args>]\nHelp: pbrun minimap2 -h''')
    IOOptions = []
    IOOptions.append(PBOption(category="IOOption", name="--ref", helpStr="Path to the reference file.", required=True, typeName=IsFileReadable))
    IOOptions.append(PBOption(category="IOOption", name="--index", helpStr="Path to a minimizer index file generated by vanilla minimap2 to reduce indexing time.", required=False, typeName=IsFileReadable))
    IOOptions.append(PBOption(category="IOOption", name="--in-fq", helpStr="Path to a query sequence file in fastq or fastq.gz format. This option can be used multiple times.", required=False, nargs='*', action='append', typeName=IsFileReadable))
    IOOptions.append(PBOption(category="IOOption", name="--in-bam", helpStr="Path to the input BAM/CRAM file.", required=False, typeName=IsBamValid))
    IOOptions.append(PBOption(category="IOOption", name="--jump-bed", short_name="-j", required=False, typeName=IsFileReadable, helpStr="Path to a BED file (.bed) used in the splice:sr preset for jumping junctions in the annotation."))
    IOOptions.append(PBOption(category="IOOption", name="--junc-bed", required=False, typeName=IsFileReadable, helpStr="Path to a BED file (.bed) used in adding bonus scores if an aligned junction matches a junction in the annotation."))
    IOOptions.append(PBOption(category="IOOption", name="--knownSites", required=False, action='append', typeName=IsFileReadable, helpStr=KNOWN_SITES_HELP))
    IOOptions.append(PBOption(category="IOOption", name="--interval-file", required=False, action='append', typeName=IsFileReadable, 
        helpStr="Path to an interval file in one of these formats: Picard-style (.interval_list or .picard), GATK-style (.list or .intervals), or BED file (.bed). This option can be used multiple times."))
    IOOptions.append(PBOption(category="IOOption", name="--out-recal-file", required=False, typeName=IsFileStreamWritable, helpStr="Path of a report file after Base Quality Score Recalibration."))
    IOOptions.append(PBOption(category="IOOption", name="--out-bam", helpStr="Path of a BAM/CRAM file after sorting.", required=True, typeName=IsFileStreamWritable))
    IOOptions.append(PBOption(category="IOOption", name="--out-duplicate-metrics", typeName=IsFileStreamWritable, helpStr="Path of duplicate metrics file after marking duplicates."))
    IOOptions.append(PBOption(category="IOOption", name="--out-qc-metrics-dir", required=False, typeName=IsDirWriteable, helpStr="Path of the directory where QC metrics will be generated."))
    minimap2_parser_iogroup = minimap2_parser.add_argument_group(ARG_GROUP_IO_OPTIONS, IO_OPTIONS)
    addToParser(minimap2_parser_iogroup, IOOptions)

    minimapOpts = minimap2OptionGenerator()
    minimap2_parser_toolgroup = minimap2_parser.add_argument_group(ARG_GROUP_TOOL_OPTIONS, TOOL_OPTIONS)
    addToParser(minimap2_parser_toolgroup, minimapOpts.allOptions)

    minimap2_parser_perfgroup = minimap2_parser.add_argument_group(ARG_GROUP_PERF_OPTIONS, PERF_OPTIONS)
    addToParser(minimap2_parser_perfgroup, minimapOpts.perfOptions)

    minimap2_parser_sysgroup = minimap2_parser.add_argument_group(ARG_GROUP_RUN_OPTIONS, RUN_OPTIONS)
    addToParser(minimap2_parser_sysgroup, sysOptionGenerator().allOptions)

    args = minimap2_parser.parse_args(argList[2:])
    return args
